#!/usr/bin/env bash
# Docker quick reference for vlm-g1
# Copy these commands as needed

echo "=== vlm-g1 Docker Quick Reference ==="
echo ""

echo "BUILD"
echo "  docker build -t vlm-g1:latest ."
echo "  # or:"
echo "  ./docker/build.sh"
echo ""

echo "RUN WITH DOCKER COMPOSE (Recommended)"
echo "  docker compose up              # Start with dashboard"
echo "  docker compose up -d           # Detached mode"
echo "  docker compose logs -f         # Follow logs"
echo "  docker compose down            # Stop"
echo "  # or:"
echo "  ./docker/run-server.sh"
echo ""

echo "RUN HEADLESS (Mic -> Agent -> Speaker)"
echo "  ./docker/run-headless.sh"
echo "  # or:"
echo "  docker run --rm -it --gpus all \\"
echo "    -v ./config.json:/workspace/config.json:ro \\"
echo "    -v vlm-g1-huggingface:/root/.cache/huggingface \\"
echo "    -v /dev/snd:/dev/snd --device /dev/snd \\"
echo "    vlm-g1:latest robo"
echo ""

echo "INTERACTIVE SHELL"
echo "  ./docker/shell.sh"
echo "  # or:"
echo "  docker exec -it vlm-g1-agent /bin/bash"
echo ""

echo "JETSON (aarch64)"
echo "  docker build -f Dockerfile.jetson -t vlm-g1:jetson ."
echo "  docker compose -f docker-compose.jetson.yml up"
echo ""

echo "COMMON TASKS"
echo "  # List images"
echo "  docker images | grep vlm-g1"
echo ""
echo "  # Check running containers"
echo "  docker ps | grep vlm-g1"
echo ""
echo "  # Clean up"
echo "  docker compose down"
echo "  docker rmi vlm-g1:latest"
echo "  docker volume prune"
echo ""
echo "  # Test GPU"
echo "  docker run --rm --gpus all nvidia/cuda:12.4.1-runtime nvidia-smi"
echo ""
echo "  # Test audio"
echo "  docker exec vlm-g1-agent arecord -L"
echo ""
echo "  # Test camera"
echo "  docker exec vlm-g1-agent ls /dev/video*"
echo ""

echo "FULL DOCS: See DOCKER.md"
echo ""
