#!/usr/bin/env bash
# Docker quick reference for Actum
# Copy these commands as needed

echo "=== Actum Docker Quick Reference ==="
echo ""

echo "BUILD"
echo "  docker build -t actum:latest ."
echo "  # or:"
echo "  ./docker/build.sh"
echo ""

echo "RUN WITH DOCKER COMPOSE (Recommended)"
echo "  docker compose up              # Start with dashboard"
echo "  docker compose up -d           # Detached mode"
echo "  docker compose logs -f         # Follow logs"
echo "  docker compose down            # Stop"
echo "  # or:"
echo "  ./docker/run-server.sh"
echo ""

echo "RUN HEADLESS (Mic -> Agent -> Speaker)"
echo "  ./docker/run-headless.sh"
echo "  # or:"
echo "  docker run --rm -it --gpus all \\"
echo "    -v ./config.json:/workspace/config.json \\"
echo "    -v actum-huggingface:/root/.cache/huggingface \\"
echo "    -v /dev/snd:/dev/snd --device /dev/snd \\"
echo "    actum:latest actum"
echo ""

echo "INTERACTIVE SHELL"
echo "  ./docker/shell.sh"
echo "  # or:"
echo "  docker exec -it actum-agent /bin/bash"
echo ""

echo "JETSON (aarch64)"
echo "  docker build -f Dockerfile.jetson -t actum:jetson ."
echo "  docker compose -f docker-compose.jetson.yml up"
echo ""

echo "COMMON TASKS"
echo "  # List images"
echo "  docker images | grep actum"
echo ""
echo "  # Check running containers"
echo "  docker ps | grep actum"
echo ""
echo "  # Clean up"
echo "  docker compose down"
echo "  docker rmi actum:latest"
echo "  docker volume prune"
echo ""
echo "  # Test GPU"
echo "  docker run --rm --gpus all nvidia/cuda:12.4.1-runtime nvidia-smi"
echo ""
echo "  # Test audio"
echo "  docker exec actum-agent arecord -L"
echo ""
echo "  # Test camera"
echo "  docker exec actum-agent ls /dev/video*"
echo ""

echo "FULL DOCS: See DOCKER.md"
echo ""
